[#1] Connect with firebase authentication
peuan/travelmate-api pull request #2
Opened 2023-07-07 14:13 UTC by rmuti56

2023-07-07 14:14 UTC, rmuti56 commented
ref: #1

2023-07-07 15:18 UTC, thasup requested changes
pls review my comments

2023-07-07 15:18 UTC, thasup commented on src/common/enums/role.enum.ts
> +  CUSTOMER = 'CUSTOMER',
I prefer `USER` rather than `CUSTOMER`

2023-07-07 15:18 UTC, thasup commented on src/migrations/1687092740504-create-user-table.ts
> +    await queryRunner.dropTable('roles');
don't any table name `roles`
not sure if it a typo or not?

2023-07-07 15:18 UTC, thasup commented on src/modules/auth/auth.module.ts
> +import { UserModule } from '../user/user.module';
why sometimes use absolute import, and some use relative import?

2023-07-07 15:18 UTC, thasup commented on src/modules/auth/services/auth.service.ts
> +import { CreateFirebaseUserDto } from '../dtos/create-firebase-user.dto';
should we using absolute import the same as the others?

2023-07-07 15:18 UTC, thasup commented on src/modules/auth/services/auth.service.ts
> +      // do nothing
it's good to have `:TODO` word to indicate what was left for editing later.
easy to search, you know? 😘

2023-07-07 15:18 UTC, thasup commented on src/modules/auth/services/auth.service.ts
> +      user = await this.firebaseAdminService
if you don't use `user` elsewhere except in the if-condition. 
why don't you write it inside like this:

```
try {
  const user = await this.firebaseAdminService
      .getAuth()
      .getUserByEmail(createFirebaseUserDto.email);
  
  if (user) {
    throw new BadRequestException({
      code: ErrorCode.EMAIL_ALREADY_EXIST,
      statusCode: HttpStatus.BAD_REQUEST,
    });
  }
} catch  {
  // TODO: do nothing
}
```

2023-07-07 15:18 UTC, thasup commented on src/modules/auth/services/auth.service.ts
> +    const newFirebaseUser = await this.firebaseAdminService
all async operations should wrap inside the try-catch block to handle errors in the future right?

who don't we wrap it all like these:

```
try {
  // check if user exists

  // create new firebase user

  // create new user from firebase email and uid

  // return new user
} catch {
  // TODO: do nothing
}
```

2023-07-07 15:18 UTC, thasup commented on src/modules/user/dtos/create-user.dto.ts
> +
remove unnecessary line

2023-07-07 15:18 UTC, thasup commented on src/modules/user/services/user.service.ts
> +    const role = await this.roleRepository.save(newRole);
```
try {
  // save a new user

  // create a new role 

  // save a new role
} catch {
  // TODO: do nothing
}
```

2023-07-08 07:42 UTC, thasup approved these changes
LGTM

2023-07-08 07:42 UTC, merged